### ISSUE TITLE
Assaults crash the game

### ISSUE THREAD

**Issue by Hector021** [muhopensores/dmc4_hook#14]
any time I'm in a room with Assaults and start attacking them the game freezes and crashes, the only fix I've found it to replace then with sth else

**Comment by SSSiyan** [comment]
Apologies to hit you with this but I'm not getting the same so:
Are you on 1.4.1? Are you on the Steam version? What settings do you have enabled? Could you try without any cheats ticked?

**Comment by Hector021** [comment]
I am on 1.4.1
my game data is from the steam version but I'm using a random cracked exe (that might be the issue I did suspect it)
I did try with nothing enabled and it still happened. but when I removed the dll file it was fine, no crashes

**Comment by SSSiyan** [comment]
Send me the exe somehow (perhaps add me on Discord @Siyan#1827) and I'll take a look

**Comment by Hector021** [comment]
Thanks! I sent u a request

**Comment by SSSiyan** [comment]
confirmed to work on steam exe, will check out this exe out of curiosity, ty!
