### ISSUE TITLE
I know its already possible to do it by royal cancelling but, could you add a option to cancel argument (while in the ground) by jumping? And also would it be possible to add a option to prevent pins from despawning unless ecstasy is used?

### ISSUE THREAD

**Issue by JetChipp** [muhopensores/dmc4_hook#15]
I know its already possible to do it by royal cancelling but, could you add a option to cancel argument (while in the ground) by jumping? And also would it be possible to add a option to prevent pins from despawning unless ecstasy is used?

**Comment by SSSiyan** [comment]
1: No (for now); you can't jump that close to the ground and I don't have much interest in looking into that right now
2: Yeah will give it a shot

**Comment by JetChipp** [comment]
Thanks

**Comment by JetChipp** [comment]
Oh and I almost forgot, could you add a option to cancel gilgamesh's combo a and b?

**Comment by SSSiyan** [comment]
added infinite pin timer, next version will have it
da070462dd3370e6ac885619977a1f8c9065f952
re gilg, no (for now :tm:)
