### ISSUE TITLE
Game crashes if enemies are spawned via twitch commands during the mission endscreen.

### ISSUE THREAD

**Issue by Monkeor** [muhopensores/dmc4_hook#18]
I wish it were as easy as "well, don't spawn them there", but Twitch always has a slight delay when broadcasting, and often times it happens by pure accident.

**Comment by SSSiyan** [comment]
Probably really easy to fix

**Comment by SSSiyan** [comment]
Phone lagged and closed it ty Motorola
I imagine it'll be as easy as adding a mission compare, thanks for the heads up!

**Comment by SSSiyan** [comment]
this was fixed in one of deeps many twitch updates, ty again
