### ISSUE TITLE
Suggestion: Random enemy swap or \SpawnRando

### ISSUE THREAD

**Issue by Monkeor** [muhopensores/dmc4_hook#24]
It would be great to have the option to set an enemy to be swapped with a random other enemy via the swapper, either chosen when each of that enemy spawns, or every scene change.

I'd also love a \SpawnRando command for Twitch integration which spawns a random enemy/boss when used.

**Comment by muhopensores** [comment]
good idea, shouldn't be too hard to shoehorn this into existing stuff. i'll probably add it when doing twitch cleanup

**Comment by muhopensores** [comment]
Twitch update has this among other things
