### ISSUE TITLE
Suggestion: Option to rebind Darkslayer to L3,R3, or another input.

### ISSUE THREAD

**Issue by Monkeor** [muhopensores/dmc4_hook#34]
I would like.

**Comment by SSSiyan** [comment]
added https://github.com/muhopensores/dmc4_hook/commit/e532ac1c2a340bf46f3656b5afea89c769c36cd5 - let me know if this is good enough, I'm quite keen
here's a build, might not be the most stable so if you don't the change I'd wait until next release [dinput8.zip](https://github.com/muhopensores/dmc4_hook/files/12777625/dinput8.zip)

**Comment by Monkeor** [comment]
The double tap is something I feel like I need to plan around mid-string because of the inherent delay to using two inputs for a swap rather than one, but I think I can acclimate eventually. I think I'd still prefer the ability to rebind the swap to a single other input, but the double tap is already worth using on its own over how it works otherwise.

**Comment by SSSiyan** [comment]
added target change darkslayer https://github.com/muhopensores/dmc4_hook/commit/13c96ed24bcdda3f5aafaba5451fbc9e9b316654
[dinput8.zip](https://github.com/muhopensores/dmc4_hook/files/12782013/dinput8.zip)

**Comment by Monkeor** [comment]
Love it, and I appreciate that you kept both as options. I'm also thankful that you included a slider for the window for double tap switching. This feels a million times smoother, so many thanks. <3
