### ISSUE TITLE
Target Change DS input disables target change when playing as Nero

### ISSUE THREAD

**Issue by Monkeor** [muhopensores/dmc4_hook#35]
Wish I had noticed earlier, but having the target change DS input toggle enabled makes it so that you can't use L3 to swap targets as Nero.

**Comment by SSSiyan** [comment]
ty, should be fixed in https://github.com/muhopensores/dmc4_hook/commit/c9ba64f039a00427f33e4568c3bb67f5e6efea8f
[dinput8.zip](https://github.com/muhopensores/dmc4_hook/files/13836863/dinput8.zip)
