### ISSUE TITLE
Multiple suggestions

### ISSUE THREAD

**Issue by SamSIM-pro** [muhopensores/dmc4_hook#41]
I didn't want to open multiple issues so I'll condense everything here:

- An option to hide all HUD with a single button
- Gun Stinger can be cancelled but if you cancel with Royal Guard, Dante slides across the area. If you hold RG, he just keeps sliding. Can you have it so that once you press RG, he stops in-place mid-stinger.
- Add Stinger to selectable cancels with the same suggestions as Gun Stinger
- Add Real Impact to selectable cancels

I'll update this if I find anything else. Thanks.

**Comment by SSSiyan** [comment]
Done, new release soon™
