### ISSUE TITLE
Suggestion: Taunt Selector

### ISSUE THREAD

**Issue by LeeroyBB** [muhopensores/dmc4_hook#44]
Can we have a taunt selector for DMC4, including Dante boss taunts? SpoilerAL has this, but it's unavailable/outdated. Useful when the style meter isn't available at areas when there's no enemies/using the enemy spawner. Thanks in advance.

**Comment by SSSiyan** [comment]
Could you send the spoilerAL script?

**Comment by LeeroyBB** [comment]
Unfortunately, I don't have SpoilerAL installed nor do I know where to download it.

**Comment by SSSiyan** [comment]
I finally got around to doing this, will be in next release. https://github.com/muhopensores/dmc4_hook/commit/d861c3f90c86cb9ab09bcd2e18e359c846aade1b

**Comment by LeeroyBB** [comment]
> I finally got around to doing this, will be in next release. [d861c3f](https://github.com/muhopensores/dmc4_hook/commit/d861c3f90c86cb9ab09bcd2e18e359c846aade1b)

You just made my day. Thank you!
