### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by aeugurauhhr** [muhopensores/dmc4_hook#45]
I believe I put something in the native folder that is part of this mod, but after I replaced the dx9 .exe with the steamless one, the mod menu would work but the game wouldn't launch as it'd stay on blackscreen. Note I was using a pirated version from RG Catalyst, released in 2012,which dates back to a 2008 version of the vanilla game.

**Comment by aeugurauhhr** [comment]
I'll be a bit annoyed if my problem is because of piracy or they secretly updated the DmC4 vanilla version on steam.

**Comment by SSSiyan** [comment]
Use a different download. I believe the one from igg works.

**Comment by aeugurauhhr** [comment]
It works but the download is incredibly slow, however I thank you for helping.
